# Generated by Django 5.0.3 on 2024-04-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0019_alter_categoria_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
