# Generated by Django 5.0.3 on 2024-04-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0020_alter_categoria_descuento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Valoraciones',
        ),
    ]
