# Generated by Django 5.0.3 on 2024-04-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0019_alter_cuenta_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='apellido',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='correo_electronico',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='username',
            field=models.CharField(max_length=25, unique=True, verbose_name='usuario'),
        ),
    ]
