# Generated by Django 5.0.3 on 2024-03-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0010_remove_carrito_cantidad_remove_carrito_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
