# Generated by Django 5.0.3 on 2024-03-27 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0011_alter_itemcarrito_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='carrito.carrito'),
        ),
    ]
