# Generated by Django 5.0.3 on 2024-04-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpedidos',
            name='sss',
            field=models.IntegerField(null=True),
        ),
    ]
