# Generated by Django 5.0.3 on 2024-04-15 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_historialpedidos_sss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialpedidos',
            name='sss',
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.ImageField(default=1, upload_to='comprobantes/', validators=[django.core.validators.validate_image_file_extension]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='correo_electronico',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
