# Generated by Django 5.0.3 on 2024-04-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_remove_historialpedidos_sss_alter_pago_comprobante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='departamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='municipio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
