# Generated by Django 5.0.3 on 2024-03-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0017_ventas'),
        ('tienda', '0013_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='tienda.producto'),
        ),
    ]
