# Generated by Django 5.0.3 on 2024-03-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0019_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='ordenado',
            field=models.BooleanField(default=False),
        ),
    ]
