# Generated by Django 5.0.3 on 2024-03-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0021_departamento_municipio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
