# Generated by Django 5.0.3 on 2024-03-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0023_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='departamento',
        ),
        migrations.AddField(
            model_name='municipio',
            name='codigo_departamento',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
