# Generated by Django 5.0.3 on 2024-03-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0024_remove_municipio_departamento_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
