# Generated by Django 5.0.3 on 2024-03-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0026_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='pedido',
            name='municpio',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='departamento',
            field=models.CharField(max_length=50),
        ),
    ]
