# Generated by Django 5.0.3 on 2024-03-31 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0027_remove_pedido_ciudad_pedido_municpio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='municpio',
            new_name='municipio',
        ),
    ]
