# Generated by Django 5.0.3 on 2024-03-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0028_rename_municpio_pedido_municipio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
