# Generated by Django 5.0.3 on 2024-04-01 03:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0030_ventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
