# Generated by Django 5.0.3 on 2024-04-01 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0032_alter_ventas_precio_alter_ventas_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
    ]
