# Generated by Django 5.0.3 on 2024-04-02 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0033_remove_pedido_productos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetallePedido',
        ),
    ]
