# Generated by Django 5.0.3 on 2024-04-03 23:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0034_delete_detallepedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
