# Generated by Django 5.0.3 on 2024-04-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0038_alter_pago_cantidad_pagada_alter_pago_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado_envio',
            field=models.CharField(choices=[('En espera de pago', 'En espera de pago'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En espera de pago', max_length=50),
        ),
    ]
