# Generated by Django 5.0.3 on 2024-04-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0040_alter_pago_estado_envio_alter_pago_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado_envio',
            field=models.CharField(choices=[('En espera de verificación', 'En espera de verificación'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En espera de verificación', max_length=50),
        ),
    ]
