# Generated by Django 5.0.3 on 2024-04-11 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0015_alter_itemcarrito_cantidad'),
        ('pedido', '0041_alter_pago_estado_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='itmeCart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carrito.itemcarrito'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.pago'),
        ),
    ]
