# Generated by Django 5.0.3 on 2024-04-11 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0015_alter_itemcarrito_cantidad'),
        ('pedido', '0042_pedido_itmecart_alter_pedido_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='itmeCart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrito.itemcarrito'),
        ),
    ]
