# Generated by Django 5.0.3 on 2024-04-11 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0043_alter_pedido_itmecart'),
        ('tienda', '0020_alter_categoria_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='itmeCart',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
            preserve_default=False,
        ),
    ]
