# Generated by Django 5.0.3 on 2024-04-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0044_remove_pedido_itmecart_remove_ventas_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
    ]
