# Generated by Django 5.0.3 on 2024-04-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0045_remove_pedido_cantidad_remove_pedido_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
