# Generated by Django 5.0.3 on 2024-04-12 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0047_historialpedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpedidos',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.pago'),
        ),
    ]
